# Generated by Django 2.2.12 on 2020-05-02 10:41

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('total_size', models.BigIntegerField(null=True)),
                ('total_file_count', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fetched_on', models.DateTimeField(null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_backupman.repository_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('paths', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('tags', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('time', models.DateTimeField()),
                ('short_id', models.CharField(editable=False, max_length=8)),
                ('parent', models.CharField(max_length=64)),
                ('tree', models.CharField(max_length=64)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fetched_on', models.DateTimeField()),
                ('total_size', models.BigIntegerField(null=True)),
                ('total_file_count', models.IntegerField(null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupman.Repository')),
            ],
            options={
                'verbose_name': 'Snapshot',
                'verbose_name_plural': 'Snapshots',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='LocalRepository',
            fields=[
                ('repository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backupman.Repository')),
                ('path', models.CharField(default='/srv/repository', max_length=200)),
            ],
            options={
                'verbose_name': 'Local Repository',
                'verbose_name_plural': 'Local Repositories',
            },
            bases=('backupman.repository',),
        ),
        migrations.CreateModel(
            name='S3Repository',
            fields=[
                ('repository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backupman.Repository')),
                ('endpoint', models.CharField(default='s3.eu-central-1.wasabisys.com', max_length=255)),
                ('bucket', models.CharField(max_length=255)),
                ('access_key_id', models.CharField(max_length=255)),
                ('secret_access_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'S3 Repository',
                'verbose_name_plural': 'S3 Repositories',
            },
            bases=('backupman.repository',),
        ),
        migrations.CreateModel(
            name='SFTPRepository',
            fields=[
                ('repository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backupman.Repository')),
                ('host', models.CharField(default='localhost', max_length=200)),
                ('user', models.CharField(blank=True, default='', max_length=200)),
                ('path', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'SFTP Repository',
                'verbose_name_plural': 'SFTP Repositories',
            },
            bases=('backupman.repository',),
        ),
        migrations.CreateModel(
            name='SnapshotPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=1000)),
                ('uid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('size', models.BigIntegerField(null=True)),
                ('mode', models.BigIntegerField()),
                ('mtime', models.DateTimeField()),
                ('atime', models.DateTimeField()),
                ('ctime', models.DateTimeField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backupman.Snapshot')),
            ],
            options={
                'verbose_name': 'Backup file',
                'verbose_name_plural': 'Backup files',
            },
        ),
    ]
