# Generated by Django 2.2.12 on 2020-05-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotpath',
            name='fetched_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='snapshotpath',
            name='atime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='snapshotpath',
            name='ctime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='snapshotpath',
            name='gid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='snapshotpath',
            name='mode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='snapshotpath',
            name='mtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='snapshotpath',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
