# Generated by Django 2.2.12 on 2020-05-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backupman', '0002_auto_20200502_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshotpath',
            options={'verbose_name': 'Snapshot path', 'verbose_name_plural': 'Snapshot paths'},
        ),
    ]
